name: Step Types

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello world!"

  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello world")
        shell: python

  say-hello-actions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d
        with:
          who-to-greet: "World"